# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbedev_test',
                'doc_host': 'https://schneider-clarify.github.io',
                'git_url': 'https://github.com/schneider-clarify/nbedev_test',
                'lib_path': 'nbedev_test'},
  'syms': {'nbedev_test.core': {'nbedev_test.core.foo': ('core.html#foo', 'nbedev_test/core.py')}}}
